///array_put_row_armor(Index,Defense,Name,Type,Resistance Element,Resistance ammount,Array,sprite)
helmetIndex[argument0,0] = argument1;
helmetIndex[argument0,1] = argument2;
helmetIndex[argument0,2] = argument3;
helmetIndex[argument0,3] = argument4;
helmetIndex[argument0,4] = argument5;
helmetIndex[argument0,5] = argument6;
helmetIndex[argument0,6] = argument7;
//argument6[argument0,5] = argument7;
