///array_put_row_armor(Index,Defense,Name,Type,Resistance Element,Resistance ammount,Array,sprite)
torsoIndex[argument0,0] = argument1;
torsoIndex[argument0,1] = argument2;
torsoIndex[argument0,2] = argument3;
torsoIndex[argument0,3] = argument4;
torsoIndex[argument0,4] = argument5;
torsoIndex[argument0,5] = argument6;
torsoIndex[argument0,6] = argument7;
//argument6[argument0,5] = argument7;
